- name: List VM instances
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - google.cloud
  vars_files:
    - ./credentials/project-name-999999.yml

  tasks:

    - name: List all instances
      gcp_compute_instance_info:
        zone: "{{ gcp_zone }}"
        project: "{{ project_name }}"
        auth_kind: serviceaccount
        service_account_contents: "{{ gce_json_contents | string }}"
      register: instance_list

    - name: Print instance names
      debug:
        msg: "Instance name: {{ item }}"
      loop: "{{ instance_list | json_query('resources[*].name') }}"
